# site settings
title: DAMP
subtitle: Department of Physics, IIT Bombay
email: dampcep@gmail.com
formspree: f/xldnvlra
description: This is the DAMP blog of the Department of Physics at IIT Bombay. <br>You can find information and posts from DAMP, latest research updates <br>and informal news here.
baseurl: "/" 
url:
author: EP DAMP Team
street_address: Department of Physics, IIT Bombay
city: Mumbai
state: MH
zip_code: 400076
country: India
phone: #(716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

socials:
  GitHub: https://github.com/epdampiitb

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
